### ISSUE TITLE
[Bug] Build fails from #3313

### ISSUE THREAD

**Issue by imnotjames** [booklore-app/booklore#3314]
### What Went Wrong?

PR #3313 was merged even while it was incomplete and had an error with the types

### How Can We Reproduce This?

1. `gradlew build`

### What Should Have Happened?

No compilation errors

### Your Setup

- Booklore version `develop` branch
- OS: Arch Linux

### Before Submitting

- [x] I've searched existing issues and confirmed this bug hasn't been reported yet
